image: node:12.12.0

stages:
  - linter
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build_image:
  stage: build
  script:
    - docker build -t api-user:1.0.0 .

linter:
  stage: linter
  script: npm run linter

tests:
  stage: test
  script: npm test

deploy:
  stage: deploy
  script: echo "Deploy !"
  only: [master]
