image: node:12.12.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build_image:
  image: docker:19.03.1
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:19.03.1-dind
  script:
    - ls
    - docker build -t api-user:1.0.0 .

linter:
  stage: test
  script: npm run linter

tests:
  stage: test
  script: npm test

deploy:
  stage: deploy
  script: echo "Deploy !"
  only: [master]
